# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
packer {
required_version = ">=1.7.5"



required_plugins {
vsphere = {
version = ">= 0.0.1"
source = "github.com/hashicorp/vsphere"
}
}
}



variable "aws_access_key" {
type = string
default = ""
}



variable "aws_region" {
type = string
default = ""
}



variable "aws_secret_key" {
type = string
default = ""
}



variable "source_ami" {
type = string
default = ""
}



variable "ssh_username" {
type = string
default = ""
}



variable "subnet_id" {
type = string
default = ""
}



variable "vpc_id" {
type = string
default = ""
}



locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }



source "amazon-ebs" "autogenerated_1" {
access_key = "${var.aws_access_key}"
ami_name = "csye6225_spring2022_${local.timestamp}"
instance_type = "t2.micro"
region = "${var.aws_region}"
secret_key = "${var.aws_secret_key}"
source_ami = "${var.source_ami}"
ssh_username = "${var.ssh_username}"
subnet_id = "${var.subnet_id}"
vpc_id = "${var.vpc_id}"
}
build {
sources = ["source.amazon-ebs.autogenerated_1"]

provisioner "file" {
source = "/Users/aravindpolepeddi/Desktop/webservice.zip"
destination = "/home/ec2-user/webservice1.zip"
}

provisioner "shell" {
script="shell/postgresql.sh"
}

provisioner "shell" {
script="shell/node.sh"
}
}