version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/webservice
   permissions:
   - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user
file_exists_behavior: OVERWRITE
hooks:
 BeforeInstall:
   - location: ./shell/codedeploy/beforeInstall.sh
     timeout: 300
     runas: ec2-user
 AfterInstall:
   - location: ./shell/codedeploy/afterinstall.sh
     timeout: 300
     runas: ec2-user
 ApplicationStart:
   - location: ./shell/codedeploy/applicationStart.sh
     timeout: 300
     runas: ec2-user
